# Generated by Django 5.2.14 on 2026-05-25 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Mijoz ismi')),
                ('phone', models.CharField(max_length=50, verbose_name='Telefon')),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Haydovchi ismi')),
                ('truck_number', models.CharField(max_length=20, verbose_name='Mashina raqami')),
                ('is_available', models.BooleanField(default=True, verbose_name='Bandmi?')),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255, verbose_name='Mijoz nomi')),
                ('destination', models.CharField(max_length=255, verbose_name='Manzil')),
                ('departure', models.CharField(max_length=255, verbose_name="Jo'nash joyi")),
                ('contract_amount', models.CharField(max_length=100, verbose_name='Dorov summasi')),
                ('advance_usd', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Avans $')),
                ('expenses_usd', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Xarajat $')),
                ('profit_sum', models.DecimalField(decimal_places=2, max_digits=15, verbose_name="Foyda (so'm)")),
                ('truck_number', models.CharField(max_length=50, verbose_name='Mashina raqami')),
                ('driver_contact', models.CharField(max_length=50, verbose_name='Haydovchi kontakti')),
                ('logist_name', models.CharField(max_length=100, verbose_name='Logist ismi')),
                ('status', models.CharField(choices=[('plan', 'Plan'), ('yolda', "Yo'lda"), ('yetkazildi', 'Yetkazildi')], max_length=50)),
                ('date_loading', models.DateField(verbose_name='Yuklash sanasi')),
            ],
        ),
    ]
