# Generated by Django 5.2.12 on 2026-05-25 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='current_latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Kenglik (Latitude)'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='current_longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Uzunlik (Longitude)'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Oxirgi yangilanish'),
        ),
    ]
